config/routes.rb
Rails.application.routes.draw do
  root 'dynamic_pages#home'

  get 'home'    => 'dynamic_pages#home'

  get 'about'   => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'ipucourse'  => 'dynamic_pages#course'

  get 'ipucollege' => 'dynamic_pages#college'

  get 'staff'   => 'dynamic_pages#staff'

  post 'rank_check'       => 'dynamic_pages#rank_check'

  post 'college_check'    => 'dynamic_pages#college_check'

  post 'course_check'     => 'dynamic_pages#course_check'

  resources :ranks
  resources :courses
  resources :colleges

end

app/models/college.rb
class College < ActiveRecord::Base
	before_save   :upcase_name
	mount_uploader :picture, PictureUploader
	validates :name, :presence => true

	has_many :ranks
	has_many :courses, :through => :ranks

	def upcase_name
      self.name = name.upcase
    end
	
end

app/models/course.rb
class Course < ActiveRecord::Base
	before_save   :upcase_name
	validates :name, :presence => true
	validates :eligibility, :presence => true
	validates :duration, :presence => true

	has_many :ranks
	has_many :colleges, :through => :ranks

	def upcase_name
      self.name = name.upcase
    end
	
end

app/models/rank.rb
class Rank < ActiveRecord::Base
	belongs_to :course
	belongs_to :college

	validates :course_id, presence: true
	validates :college_id, presence: true
  	validates :dgen, presence: true
  	validates :odgen, presence: true

	validates :dgen, :numericality => { :greater_than => 0 }
	validates :odgen, :numericality => { :greater_than => 0 }

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:name, :address, :phone, :picture)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name,:eligibility,:duration)
    end
end

app/controllers/dynamic_pages_controller.rb
class DynamicPagesController < ApplicationController

def rank_check
    @rank = params[:dynamic_pages][:rank]
    @course_id = params[:dynamic_pages][:course_id]
    @category = params[:dynamic_pages][:category]

      if @category == 'DGEN'
        @result = College.select(:name).where("dgen >= ?", @rank).where("course_id = ?", @course_id).order("ranks.dgen").joins(:ranks)
      else
        
        @result = College.select(:name).where("odgen >= ?", @rank).where("course_id = ?", @course_id).order("ranks.odgen").joins(:ranks)
      end 
     
end

def course_check
    @course = Course.find(params[:dynamic_pages][:id])
       
end

def college_check
    @college = College.find(params[:dynamic_pages][:id])

end

end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :set_rank, only: [:show, :edit, :update, :destroy]

  # GET /ranks
  # GET /ranks.json
  def index
    @ranks = Rank.all
  end

  # GET /ranks/1
  # GET /ranks/1.json
  def show
  end

  # GET /ranks/new
  def new
    @rank = Rank.new
    # @course = Course.all
    # @college = College.all
  end

  # GET /ranks/1/edit
  def edit
  end

  # POST /ranks
  # POST /ranks.json
  def create
    @rank = Rank.new(rank_params)    

    respond_to do |format|
      if @rank.save
        format.html { redirect_to @rank, notice: 'Rank was successfully created.' }
        format.json { render :show, status: :created, location: @rank }
      else
        format.html { render :new }
        format.json { render json: @rank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ranks/1
  # PATCH/PUT /ranks/1.json
  def update
    respond_to do |format|
      if @rank.update(rank_params)
        format.html { redirect_to @rank, notice: 'Rank was successfully updated.' }
        format.json { render :show, status: :ok, location: @rank }
      else
        format.html { render :edit }
        format.json { render json: @rank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ranks/1
  # DELETE /ranks/1.json
  def destroy
    @rank.destroy
    respond_to do |format|
      format.html { redirect_to ranks_url, notice: 'Rank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rank
      @rank = Rank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rank_params
      params.require(:rank).permit(:college_id, :course_id, :dgen, :odgen)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/colleges/_form.html.erb
<% provide(:title, "Staff") %>
 <div class="row">
          <div class="col-md-6 col-md-offset-3">
<%= form_for(@college, html: {multipart: true}) do |f| %>
  <% if @college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% @college.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <span class="picture">
    <%= f.label :picture %><br>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>

app/views/colleges/edit.html.erb
 <div class="row">
          <div class="col-md-6 col-md-offset-3">
<h1>Editing College</h1>

<%= render 'form' %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>
</div>
</div>

app/views/colleges/index.html.erb
<% provide(:title, "Staff") %>
<p id="notice"><%= notice %></p>

<h1>Listing Colleges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.name %></td>
        <td><%= college.address %></td>
        <td><%= college.phone %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College', new_college_path %>
<%= link_to 'Staff Page', staff_path %>

app/views/colleges/new.html.erb
<h1>New College</h1>

<%= render 'form' %>

<%= link_to 'Back', colleges_path %>

app/views/colleges/show.html.erb
<% provide(:title, "Staff") %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @college.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @college.phone %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>

app/views/courses/_form.html.erb
<% provide(:title, "Staff") %>

 <div class="row">
          <div class="col-md-6 col-md-offset-3">
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :eligibility %><br>
    <%= f.text_field :eligibility %>
  </div>

  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>

app/views/courses/edit.html.erb
 <div class="row">
          <div class="col-md-6 col-md-offset-3">
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>
</div>
</div>

app/views/courses/index.html.erb
<% provide(:title, "Staff") %>
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Eligibility</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.eligibility %></td>
        <td><%= course.duration %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>
<%= link_to 'Staff Page', staff_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<% provide(:title, "Staff") %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Eligibility:</strong>
  <%= @course.eligibility %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @course.duration %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/dynamic_pages/college.html.erb
<% provide(:title, "College Finder") %>
<div class="center jumbotron">

 	<h3>College Finder</h3><br>
  
     <div class="row">
          <div class="col-md-6 col-md-offset-3">
		      <%= form_for(:dynamic_pages, url: college_check_path) do |f| %>

		      <div class="field">
				    <%= f.label :id, 'Select College' %><br>
				    <%= f.collection_select(:id, College.order(:name), :id, :name, {}) %>
			  </div>

			  <div>
				   <%= f.submit "Submit", class: "btn btn-primary"  %>
			  </div>

			  <% end %>
	  		</div>
	</div>
</div>

app/views/dynamic_pages/college_check.html.erb
<% provide(:title, "College Finder") %>

 <div class="row">
         <div class="col-md-6 col-md-offset-3">
         	<div align="center">
<%= image_tag @college.picture.url if @college.picture? %><br><br>
<strong>College Name : </strong><%= @college.name %><br><br>
<strong>Address : </strong><%= @college.address %><br><br>
<strong>Phone : </strong><%= @college.phone %><br><br>
			</div>
		 </div> 
</div>

app/views/dynamic_pages/course.html.erb
<% provide(:title, "Course Finder") %>
<div class="center jumbotron">
    	
      <h3>Course Finder</h3><br>

   <div class="row">
      <div class="col-md-6 col-md-offset-3">
          <%= form_for(:dynamic_pages, url: course_check_path) do |f| %>

          <div class="field">
    		    <%= f.label :id, 'Select Course'  %><br>
    		    <%= f.collection_select(:id, Course.order(:name), :id, :name, {}) %>
      	  </div>

      	  <div>
    		    <%= f.submit "Submit", class: "btn btn-primary"  %>
    	    </div>

    	   <% end %>
      </div>
    </div>
</div>

app/views/dynamic_pages/course_check.html.erb
<% provide(:title, "Course Finder") %>
 <div class="row">
         <div class="col-md-6 col-md-offset-3">
         	<div align="center">
<strong>Course Name : </strong><%= @course.name %><br><br>
<strong>EligibilIty : </strong><%= @course.eligibility %><br><br>
<strong>Duration : </strong><%= @course.duration %><br><br>
			</div>
		 </div> 
</div>

app/views/dynamic_pages/home.html.erb
<% provide(:title, "Home | Rank Analyser") %>
<div class="center jumbotron">
    <h1>Welcome to IPU Portal</h1>
    	
      <h3>Rank Analyser</h3><br>
    <div class="row">
          <div class="col-md-6 col-md-offset-3">
              <%= form_for(:dynamic_pages, url: rank_check_path) do |f| %>
              
          	<div class="field">
          	  <%= f.label :course_id, 'Select Course'  %><br>
          	  <%= f.collection_select(:course_id, Course.order(:name), :id, :name, {}) %>
          	</div>

        	  <div class="field">
        	    <%= f.label :category, 'Select Category'  %><br>
        	    <%= f.select :category, options_for_select(["DGEN", "ODGEN"])   %>
        	  </div>

            <div class="field">
              <%= f.label :rank, 'Enter Rank' %><br>
              <%= f.number_field :rank, :in => 1..30000, :required => true %>
            </div>

            <div>
        		    <%= f.submit "Submit", class: "btn btn-primary"  %>
        	  </div>

        	  <% end %>

          </div>
    </div>
</div>
  

app/views/dynamic_pages/rank_check.html.erb
<% provide(:title, "Rank Analyser") %>
<div class="row">
          <div class="col-md-6 col-md-offset-3">
<table class="table table-striped">
  <thead>
    <tr>
      <th>S.No</th>
      <th>College Name</th>
    </tr>
  </thead>
  <tbody>
      <% @count = 0 %> 
      <% @result.each do |result| %> 
      <tr>
        <th scope="row"><%= @count += 1 %></th>
        <td><%= result.name %></td>
      </tr>
      <% end %> 
  </tbody>
</table>
            </div>
</div>

app/views/dynamic_pages/staff.html.erb
<% provide(:title, "Staff") %>
<h1>Administrator Panel</h1>
<strong>College Index Page : </strong><%= link_to "view index", colleges_path %><br><br>
<strong>Course Index Page : </strong><%= link_to "view index", courses_path %><br><br>
<strong>Rank Index Page : </strong><%= link_to "view index", ranks_path %><br><br>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
	©IPU Portal
	</small>
		<nav>
				<ul>
					<li><%= link_to "About", about_path%></li>
					<li><%= link_to "Contact", contact_path%></li>
				</ul>

			</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navabar-fixed-top navbar-inverse" id="header">
		
			<nav>
      <div class="container">
      <div class="navbar-header page-scroll">
               
                 <%= link_to "ipu portal", '/', id: "logo" %>
                </div>
        
				  <ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home",root_path %></li>
					<li><%= link_to "Courses",ipucourse_path %></li>
          <li><%= link_to "Colleges",ipucollege_path %></li>
          <li><%= link_to "Forum", 'http://localhost:3001/' %></li>
          </ul>
          
         
				
       
      </div>
			</nav>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | IPU Portal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/ranks/_form.html.erb
<% provide(:title, "Staff") %>
 <div class="row">
          <div class="col-md-6 col-md-offset-3">
<%= form_for(@rank) do |f| %>
  <% if @rank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rank.errors.count, "error") %> prohibited this rank from being saved:</h2>

      <ul>
      <% @rank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    

  <div class="field">
    <%= f.label :college_id %><br>
    <%= f.collection_select(:college_id, College.order(:name), :id, :name, {}) %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.collection_select(:course_id, Course.order(:name), :id, :name, {}) %>
  </div>


  <div class="field">
    <%= f.label :dgen %><br>
    <%= f.number_field :dgen %>
  </div>
  <div class="field">
    <%= f.label :odgen %><br>
    <%= f.number_field :odgen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>

app/views/ranks/edit.html.erb
 <div class="row">
          <div class="col-md-6 col-md-offset-3">
<h1>Editing Rank</h1>

<%= render 'form' %>

<%= link_to 'Show', @rank %> |
<%= link_to 'Back', ranks_path %>
</div>
</div>

app/views/ranks/index.html.erb
<% provide(:title, "Staff") %>
<p id="notice"><%= notice %></p>

<h1>Listing Ranks</h1>

<table>
  <thead>
    <tr>
      <th>CollegeId</th>
      <th>CourseId</th>
      <th>CollegeName</th>
      <th>CourseName</th>
      <th>Dgen</th>
      <th>Odgen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ranks.each do |rank| %>
      <tr>
        <td><%= rank.college_id %></td>
        <td><%= rank.course_id %></td>
        <% @collegetest = rank.college_id %>
        <% @college_name = College.select(:name).where(:id => @collegetest) %>
      
        <% @college_name.each do |college_name| %>

        <td><%= college_name.name %></td>

        <% end %>
        
        <% @coursetest = rank.course_id %>
        <% @course_name = Course.select(:name).where(:id => @coursetest) %>
      
        <% @course_name.each do |course_name| %>

        <td><%= course_name.name %></td>

        <% end %>
        <td><%= rank.dgen %></td>
        <td><%= rank.odgen %></td>
        <td><%= link_to 'Show', rank %></td>
        <td><%= link_to 'Edit', edit_rank_path(rank) %></td>
        <td><%= link_to 'Destroy', rank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rank', new_rank_path %>
<%= link_to 'Staff Page', staff_path %>

app/views/ranks/new.html.erb
<h1>New Rank</h1>

<%= render 'form' %>

<%= link_to 'Back', ranks_path %>

app/views/ranks/show.html.erb
<% provide(:title, "Staff") %>
<p id="notice"><%= notice %></p>

<p>
  <strong>CollegeId:</strong>
  <%= @rank.college_id %>
</p>

<p>
  <strong>CourseId:</strong>
  <%= @rank.course_id %>
</p>


<p>
  <strong>CollegeName:</strong>
  <% @collegetest = @rank.college_id %>
        <% @college_name = College.select(:name).where(:id => @collegetest) %>
      
        <% @college_name.each do |college_name| %>

        <%= college_name.name %>

        <% end %>
  
</p>

<p>
  <strong>CourseName:</strong>
  <% @coursetest = @rank.course_id %>
        <% @course_name = Course.select(:name).where(:id => @coursetest) %>
      
        <% @course_name.each do |course_name| %>

        <%= course_name.name %>

        <% end %>
</p>

<p>
  <strong>Dgen:</strong>
  <%= @rank.dgen %>
</p>

<p>
  <strong>Odgen:</strong>
  <%= @rank.odgen %>
</p>

<%= link_to 'Edit', edit_rank_path(@rank) %> |
<%= link_to 'Back', ranks_path %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>